import { useScrollReveal } from "@/hooks/use-scroll-reveal";

const stats = [
  { value: "90", unit: "sec", label: "HIPAA authorization generated by Donna", sub: "From case submission to signed auth" },
  { value: "6", unit: "", label: "AI QUALITY CHECKS ON EVERY CASE", sub: "Patient identity · Auth valid · Completeness · Provider · Duplicates · Billing" },
  { value: "$25", unit: "", label: "NO-RECORDS-FOUND FEE", sub: "Industry-low flat fee. Most providers charge the full amount regardless." },
  { value: "0", unit: "", label: "CASES DELIVERED WITHOUT HUMAN REVIEW", sub: "Every case. No exceptions. This is a firm rule." },
];

const StatsSection = () => {
  const { ref, isVisible } = useScrollReveal();

  return (
    <section className="section-dark py-20 lg:py-28" ref={ref}>
      <div className="container">
        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-8 lg:gap-12">
          {stats.map((stat, i) => (
            <div
              key={stat.label}
              className={`text-center ${isVisible ? "animate-fade-up" : "opacity-0"}`}
              style={{ animationDelay: `${i * 0.1}s` }}
            >
              <div className="flex items-baseline justify-center gap-1 mb-3">
                <span className="text-5xl lg:text-6xl font-bold text-teal tabular-nums">
                  {stat.value}
                </span>
                {stat.unit && (
                  <span className="text-teal/70 text-xl font-semibold">
                    {stat.unit}
                  </span>
                )}
              </div>
              <p className="text-white font-bold text-xs tracking-wider uppercase mb-2">
                {stat.label}
              </p>
              <p className="text-white/50 text-sm">{stat.sub}</p>
            </div>
          ))}
        </div>

        {/* CTA */}
        <div className={`text-center mt-12 ${isVisible ? "animate-fade-up" : "opacity-0"}`} style={{ animationDelay: "0.5s" }}>
          <a href="#process" className="inline-flex items-center gap-2 text-teal font-semibold text-sm hover:underline transition-colors">
            See how it works →
          </a>
        </div>
      </div>
    </section>
  );
};

export default StatsSection;
